echo go away

diff --git a/org1/builders-config.yaml b/org1/builders-config.yaml
--- a/org1/builders-config.yaml
+++ b/org1/builders-config.yaml
@@ -27,18 +27,18 @@ data:
 
         # use jq to extract the chaincode type from metadata.json and exit with
         # success if the chaincode type is golang
-        echo "=Begin-detect-" >> /share/detect.log
-        cat "$CHAINCODE_METADATA_DIR/metadata.json" >> /share/detect.log
-        echo "=1===" >> /share/detect.log
-        echo $(cat "$CHAINCODE_METADATA_DIR/metadata.json" | sed -e 's/[{}]/''/g' | awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'type'\042/){print $(i+1)}}}' | tr -d '"') >> /share/detect.log
-        echo "=2===" >> /share/detect.log
+        #echo "=Begin-detect-" >> /share/detect.log
+        #cat "$CHAINCODE_METADATA_DIR/metadata.json" >> /share/detect.log
+        #echo "=1===" >> /share/detect.log
+        #echo $(cat "$CHAINCODE_METADATA_DIR/metadata.json" | sed -e 's/[{}]/''/g' | awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'type'\042/){print $(i+1)}}}' | tr -d '"') >> /share/detect.log
+        #echo "=2===" >> /share/detect.log
         #type=$(cat "$CHAINCODE_METADATA_DIR/metadata.json" | sed -e 's/[{}]/''/g' | awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'type'\042/){print $(i+1)}}}' | tr -d '"')
         #echo $type >> /share/detect.log
         if [ $(cat "$CHAINCODE_METADATA_DIR/metadata.json" | sed -e 's/[{}]/''/g' | awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'type'\042/){print $(i+1)}}}' | tr -d '"') == "external" ]; then
-            echo "==End-detect-exit 0-" >> /share/detect.log
+            #echo "==End-detect-exit 0-" >> /share/detect.log
             exit 0
         fi
-        echo "==End-detect-exit 1-" >> /share/detect.log
+        #echo "==End-detect-exit 1-" >> /share/detect.log
         exit 1
 
     build: |
@@ -62,15 +62,15 @@ data:
 
         set -euo pipefail
 
-        echo "=Begin-build-" >> /share/detect.log
-        echo "CHAINCODE_SOURCE_DIR=$CHAINCODE_SOURCE_DIR" >> /share/detect.log
-        echo "CHAINCODE_METADATA_DIR=$CHAINCODE_METADATA_DIR" >> /share/detect.log
-        echo "BUILD_OUTPUT_DIR=$BUILD_OUTPUT_DIR" >> /share/detect.log
+        #echo "=Begin-build-" >> /share/detect.log
+        #echo "CHAINCODE_SOURCE_DIR=$CHAINCODE_SOURCE_DIR" >> /share/detect.log
+        #echo "CHAINCODE_METADATA_DIR=$CHAINCODE_METADATA_DIR" >> /share/detect.log
+        #echo "BUILD_OUTPUT_DIR=$BUILD_OUTPUT_DIR" >> /share/detect.log
 
         #external chaincodes expect connection.json file in the chaincode package
         if [ ! -f "$CHAINCODE_SOURCE_DIR/connection.json" ]; then
             >&2 echo "$CHAINCODE_SOURCE_DIR/connection.json not found"
-            echo "$CHAINCODE_SOURCE_DIR/connection.json not found =End-build exit 1-" >> /share/detect.log
+            #echo "$CHAINCODE_SOURCE_DIR/connection.json not found =End-build exit 1-" >> /share/detect.log
             exit 1
         fi
 
@@ -81,7 +81,7 @@ data:
             cp -a $CHAINCODE_SOURCE_DIR/metadata $BUILD_OUTPUT_DIR/metadata
         fi
 
-        echo "=End-build exit 0-" >> /share/detect.log
+        #echo "=End-build exit 0-" >> /share/detect.log
         exit 0
 
     release: |
@@ -102,9 +102,9 @@ data:
         BUILD_OUTPUT_DIR="$1"
         RELEASE_OUTPUT_DIR="$2"
 
-        echo "=Begin-release-" >> /share/detect.log
-        echo "BUILD_OUTPUT_DIR=$BUILD_OUTPUT_DIR" >> /share/detect.log
-        echo "RELEASE_OUTPUT_DIR=$RELEASE_OUTPUT_DIR" >> /share/detect.log
+        #echo "=Begin-release-" >> /share/detect.log
+        #echo "BUILD_OUTPUT_DIR=$BUILD_OUTPUT_DIR" >> /share/detect.log
+        #echo "RELEASE_OUTPUT_DIR=$RELEASE_OUTPUT_DIR" >> /share/detect.log
 
         # copy indexes from metadata/* to the output directory
         # if [ -d "$BUILD_OUTPUT_DIR/metadata" ] ; then
@@ -118,11 +118,11 @@ data:
 
         #if tls_required is true, copy TLS files (using above example, the fully qualified path for these fils would be "$RELEASE_OUTPUT_DIR"/chaincode/server/tls)
 
-        echo "=End-release- exit 0" >> /share/detect.log
+        #echo "=End-release- exit 0" >> /share/detect.log
         exit 0
         fi
 
-        echo "=End-release- exit 1" >> /share/detect.log
+        #echo "=End-release- exit 1" >> /share/detect.log
         exit 1
     core.yaml: |
         # Copyright IBM Corp. All Rights Reserved.
